export const VERSION = '0.0.0'

export * from './types/index.js'
export * from './config/index.js'
export * from './rng/index.js'
export * from './geometry/index.js'
export * from './terrain/index.js'
export * from './action-result/index.js'
export * from './rules/turn-rules.js'
export * from './resolution/movement.js'
export * from './resolution/flare.js'
export * from './resolution/shell.js'
export * from './resolution/damage.js'
export * from './worldview/build.js'
export * from './result/ranking.js'
export * from './match/fake-agents.js'
export * from './match/orchestration.js'
